"""Size-cap ratchet: CLAUDE.md's <500/<100/<50 caps, enforced by AST (D4).

**Metric** (decided 2026-09-22, Epic 4 pre-work — see
``_bmad-output/implementation-artifacts/epic4-prework-spec.md``): the set of
distinct source lines occupied by ``ast.stmt`` nodes, excluding docstring
expressions. A compound statement (``if``/``for``/``while``/``with``/``try``/
``def``/``class``/``match``) contributes only its header line to whatever
scope it is directly nested in — its own body is measured separately and
rolled up into it. Concretely:

- A function's size is its own statements' lines, with a nested closure's
  lines folded directly in (ruling 3) — the closure gets **no key of its
  own**.
- A class's size is its own directly-owned statements' lines (field
  annotations, control flow) plus the sum of its methods' own sizes — each
  method **does** get its own key, ``Class.method``.
- A file's size is its own top-level statements' lines plus the sum of its
  classes' and top-level functions' sizes.

**Metric rulings** (same date, so the first person to hit one does not
relitigate it):

1. Field annotations count — a Pydantic/dataclass ``name: type = default``
   line is an ``AnnAssign`` statement like any other.
2. Multi-line literals count every line they occupy. A docstring is the only
   multi-line expression excluded, and only in docstring position (first
   statement of a module/class/function body).
3. Nested functions roll up into their parent and are not keyed separately;
   methods roll up into their class and *are* keyed; classes and functions
   both roll up into the file.

**Two caps, two enforcement shapes:**

- **File cap (hard)** — 500 lines, with a 3-entry allowlist carrying each
  listed file's recorded ceiling. A listed file may not exceed its ceiling;
  any other file may not exceed 500.
- **Class/function cap (ratchet)** — a ``SIZE_BASELINE`` mapping generated
  once from the tree's overages at D4's landing. The guard fails when (a) an
  unlisted class/function exceeds its cap, (b) a listed one exceeds its
  recorded value, or (c) a listed one now measures **at or under** its cap —
  stale entries must be removed, so the baseline only shrinks. Shrinking
  without dropping under the cap needs no edit (the entry is a ceiling, not
  an exact value).

Regenerate the baseline after a deliberate split with:
``python -m tests.unit.governance.test_size_caps --print-baseline``
"""

from __future__ import annotations

import ast
import sys
from dataclasses import dataclass, field
from pathlib import Path

import pytest

pytestmark = pytest.mark.unit

REPO_ROOT = Path(__file__).resolve().parents[3]
SRC_ROOT = REPO_ROOT / "src"

FILE_CAP = 500
CLASS_CAP = 100
FUNCTION_CAP = 50

#: Files whose *executable-statement* size exceeds FILE_CAP, each carrying the
#: ceiling it may not cross. To exceed a cap deliberately, add the entry with
#: a one-line reason in the same commit (CLAUDE.md's disclose-and-record step).
FILE_ALLOWLIST: dict[str, int] = {
    "src/core/backtest_runner.py": 952,
    "src/services/data_catalog.py": 635,
    "src/api/ui/backtests.py": 524,
}

#: Ratchet baseline — every class/function over its cap when this guard
#: landed (2026-09-22, Epic 4 pre-work), generated by
#: ``python -m tests.unit.governance.test_size_caps --print-baseline``. Each
#: entry is a ceiling, not an exact value: shrinking without dropping under
#: the cap needs no edit, but a stale entry (dropped to or under the cap) must
#: be removed, and growth past the recorded ceiling fails.
#:
#: 95 entries, not the 98 the pre-work spec's own reconnaissance estimated —
#: this tool's count is the authoritative one now that it exists and is
#: tested; the 11 named examples and 3 file totals that reconnaissance did
#: report were independently re-measured against this implementation and
#: match it exactly (`src/config.py::IBKRSettings` measures 101, confirming
#: metric ruling 1 — field annotations count).
#:
#: 93 since 2026-09-22 (Story 4.4 test fix): the two ``custom/`` submodule
#: entries (``apolo_rsi``, ``bollinger_reversal``) left with the submodule's
#: exclusion from the walk — see ``_iter_src_files``.
SIZE_BASELINE: dict[str, int] = {
    "src/api/models/backtest_detail.py::build_metrics_panel": 99,
    "src/api/rest/indicators.py::_compute_bollinger_indicators": 54,
    "src/api/rest/trades.py::export_trades": 93,
    "src/api/stats_service.py::_build_ticker_stats": 72,
    "src/api/ui/backtests.py::backtest_list": 64,
    "src/api/ui/backtests.py::backtest_list_fragment": 58,
    "src/api/ui/backtests.py::run_backtest_submit": 126,
    "src/api/ui/explorer.py::chart_panel_fragment": 89,
    "src/cli/commands/_backtest_helpers.py::_load_catalog_data": 74,
    "src/cli/commands/_backtest_helpers.py::_resolve_cli_mode": 66,
    "src/cli/commands/backtest.py::run_backtest": 174,
    "src/cli/commands/backtest.py::run_multi_backtest": 93,
    "src/cli/commands/catalog.py::restamp_venues": 63,
    "src/cli/commands/compare.py::_compare_backtests_sync": 60,
    "src/cli/commands/compare.py::_display_comparison_table": 61,
    "src/cli/commands/data.py::check_data": 83,
    "src/cli/commands/data.py::fetch": 64,
    "src/cli/commands/data.py::import_data": 73,
    "src/cli/commands/data.py::list_data": 108,
    "src/cli/commands/history.py::_display_strategy_summary": 60,
    "src/cli/commands/history.py::_list_history_sync": 106,
    "src/cli/commands/import_data.py::_print_dry_run_report": 87,
    "src/cli/commands/import_data.py::_run_import": 105,
    "src/cli/commands/report.py::_generate_json_report": 51,
    "src/cli/commands/reproduce.py::_reproduce_backtest_async": 164,
    "src/cli/commands/show.py::_display_performance_metrics": 64,
    "src/config.py::IBKRSettings": 101,
    "src/core/analytics.py::PortfolioAnalytics": 150,
    "src/core/analytics.py::PortfolioAnalytics.calculate_performance_attribution": 55,
    "src/core/backtest_orchestrator.py::BacktestOrchestrator": 325,
    "src/core/backtest_orchestrator.py::BacktestOrchestrator._persist_results": 57,
    "src/core/backtest_runner.py::MinimalBacktestRunner": 926,
    "src/core/backtest_runner.py::MinimalBacktestRunner._extract_results": 111,
    "src/core/backtest_runner.py::MinimalBacktestRunner._persist_backtest_results": 100,
    "src/core/backtest_runner.py::MinimalBacktestRunner.run_backtest_with_catalog_data": 123,
    "src/core/backtest_runner.py::MinimalBacktestRunner.run_backtest_with_database": 76,
    "src/core/backtest_runner.py::MinimalBacktestRunner.run_backtest_with_strategy_type": 74,
    "src/core/backtest_runner.py::MinimalBacktestRunner.run_from_config_object": 107,
    "src/core/backtest_runner.py::MinimalBacktestRunner.run_from_config_with_catalog_data": 66,
    "src/core/backtest_runner.py::MinimalBacktestRunner.run_sma_backtest": 56,
    "src/core/live_bar_observer.py::LiveBarObserver": 120,
    "src/core/live_connection_monitor.py::ConnectionMonitor": 118,
    "src/core/live_node_builder.py::build_trading_node_config": 128,
    "src/core/live_order_path.py::OrderEventObserver": 165,
    # Story 4.4, 400 -> 414: warm-up wiring (arm in `_phase_warmup`, instrument
    # + settle per strategy, the stop/reclaim predicate the wait reads); the
    # watch itself is its own module. Story 4.2, 414 -> 424: reconcile seam,
    # pre-reconciliation snapshot, trading latch; the logic is live_startup_reconcile.py
    # (file budget made first by moving stop_degraded_strategies out, 499 -> 481).
    "src/core/live_session_runner.py::LiveSessionRunner": 424,
    "src/core/live_session_runner.py::LiveSessionRunner.run": 66,
    "src/core/live_session_steady_state.py::SessionSteadyState": 120,
    "src/core/live_strategy_guard.py::StrategyGuard": 121,
    "src/core/live_trade_recorder.py::TradeRecorder": 164,
    "src/core/metrics.py::PerformanceCalculator": 128,
    "src/core/metrics.py::PerformanceCalculator.calculate_metrics_from_data": 55,
    "src/core/results_extractor.py::ResultsExtractor": 154,
    "src/core/results_extractor.py::ResultsExtractor.extract_results": 85,
    # Story 4.4, 103 -> 110: AR40 warm-up inline in `on_start` + the history
    # callback, deliberately not hidden in a helper so AC #2's inspection reads
    # the three Nautilus calls in the strategy file itself.
    "src/core/strategies/sma_crossover.py::SMACrossover": 110,
    # Story 4.4, 58 -> 52 (shrank): registered SMAs replaced the deque average.
    "src/core/strategies/sma_momentum.py::SMAMomentum.on_bar": 52,
    "src/core/strategy_registry.py::StrategyRegistry": 101,
    "src/db/repositories/backtest_repository.py::BacktestRepository": 236,
    "src/db/repositories/backtest_repository_sync.py::SyncBacktestRepository": 153,
    "src/db/repositories/catalog_instrument_repository.py::CatalogInstrumentRepository": 122,
    "src/db/repositories/catalog_instrument_repository.py::SyncCatalogInstrumentRepository": 107,
    "src/models/backtest_request.py::BacktestRequest": 176,
    "src/models/price_validation_report.py::evaluate_ticker_deviation": 64,
    "src/services/backtest_persistence.py::BacktestPersistenceService": 274,
    "src/services/backtest_persistence.py::BacktestPersistenceService._extract_and_validate_metrics": 58,  # noqa: E501
    "src/services/backtest_persistence.py::BacktestPersistenceService.save_trades_from_positions": 137,  # noqa: E501
    "src/services/backtest_query.py::BacktestQueryService": 108,
    "src/services/comparison_renderer.py::render_comparison_table": 66,
    "src/services/csv_loader.py::CSVLoader": 205,
    "src/services/csv_loader.py::CSVLoader.load_file": 65,
    "src/services/data_catalog.py::DataCatalogService": 612,
    "src/services/data_catalog.py::DataCatalogService._fetch_from_ibkr_with_retry": 52,
    "src/services/data_catalog.py::DataCatalogService._rebuild_availability_cache": 106,
    "src/services/data_catalog.py::DataCatalogService.query_bars": 61,
    "src/services/database_repository.py::DatabaseRepository": 128,
    "src/services/firstrate/backtest_loader.py::load_from_catalog": 70,
    "src/services/firstrate/import_service.py::ImportService": 373,
    "src/services/firstrate/import_service.py::ImportService._import_ticker": 135,
    "src/services/firstrate/import_service.py::ImportService.import_directory": 59,
    "src/services/firstrate/venue_restamp_plan.py::build_restamp_plan": 71,
    "src/services/ibkr_client.py::IBKRHistoricalClient": 122,
    "src/services/kraken_client.py::KrakenHistoricalClient": 145,
    "src/services/metadata/fmp_client.py::FMPClient": 101,
    "src/services/portfolio.py::PortfolioService": 143,
    "src/services/reports/csv_exporter.py::CSVExporter": 218,
    "src/services/reports/json_exporter.py::JSONExporter": 107,
    "src/services/reports/json_exporter.py::JSONExporter.export_trades": 54,
    "src/services/reports/text_report.py::TextReportGenerator": 241,
    "src/services/results_store.py::ResultsStore": 115,
    "src/services/trade_analytics.py::calculate_drawdowns": 73,
    "src/services/trade_analytics.py::calculate_trade_statistics": 103,
    "src/utils/data_wrangler.py::MarketDataWrangler": 128,
    "src/utils/logging.py::configure_logging": 58,
    "src/utils/mock_data.py::generate_mock_bars": 55,
}

_COMPOUND_TYPES: tuple[type, ...] = (
    ast.If,
    ast.For,
    ast.AsyncFor,
    ast.While,
    ast.With,
    ast.AsyncWith,
    ast.Try,
    ast.TryStar,
    ast.Match,
)
_DEF_TYPES: tuple[type, ...] = (ast.FunctionDef, ast.AsyncFunctionDef)


def _is_docstring(stmt: ast.stmt, index: int) -> bool:
    return (
        index == 0
        and isinstance(stmt, ast.Expr)
        and isinstance(stmt.value, ast.Constant)
        and isinstance(stmt.value.value, str)
    )


def _sub_bodies(stmt: ast.stmt) -> list[list[ast.stmt]]:
    """Every nested statement list a non-def/class compound statement owns."""
    if isinstance(stmt, ast.If):
        return [stmt.body, stmt.orelse]
    if isinstance(stmt, (ast.For, ast.AsyncFor, ast.While)):
        return [stmt.body, stmt.orelse]
    if isinstance(stmt, (ast.With, ast.AsyncWith)):
        return [stmt.body]
    if isinstance(stmt, (ast.Try, ast.TryStar)):
        bodies = [stmt.body, stmt.orelse, stmt.finalbody]
        bodies.extend(handler.body for handler in stmt.handlers)
        return bodies
    if isinstance(stmt, ast.Match):
        return [case.body for case in stmt.cases]
    return []


def _fold_lines(stmts: list[ast.stmt]) -> set[int]:
    """Executable-statement lines for a body, folding nested defs/classes
    directly in rather than keying them separately (ruling 3). Used for a
    function's own body, and for any compound statement's children.
    """
    lines: set[int] = set()
    for index, stmt in enumerate(stmts):
        if _is_docstring(stmt, index):
            continue
        if isinstance(stmt, (*_DEF_TYPES, ast.ClassDef)):
            lines.add(stmt.lineno)
            lines |= _fold_lines(stmt.body)
            continue
        if isinstance(stmt, _COMPOUND_TYPES):
            lines.add(stmt.lineno)
            for sub in _sub_bodies(stmt):
                lines |= _fold_lines(sub)
            continue
        end = stmt.end_lineno or stmt.lineno
        lines.update(range(stmt.lineno, end + 1))
    return lines


def _measure_class_body(
    stmts: list[ast.stmt], qualname_prefix: str, functions_out: dict[str, int]
) -> int:
    """A class's own total size: its directly-owned lines plus every
    method's own size, each method recorded under ``Class.method``. A class
    nested inside a class folds into the outer one with no key of its own —
    the repo has no such shape today, and the caps are about statement
    volume, not nesting depth.
    """
    own_lines: set[int] = set()
    methods_total = 0
    for index, stmt in enumerate(stmts):
        if _is_docstring(stmt, index):
            continue
        if isinstance(stmt, _DEF_TYPES):
            # The method's own header line counts toward *its* total (below),
            # not the class's `own_lines` — added once, via `methods_total`.
            qualname = f"{qualname_prefix}.{stmt.name}"
            size = 1 + len(_fold_lines(stmt.body))
            functions_out[qualname] = size
            methods_total += size
            continue
        if isinstance(stmt, ast.ClassDef):
            methods_total += 1 + _measure_class_body(
                stmt.body, f"{qualname_prefix}.{stmt.name}", functions_out
            )
            continue
        if isinstance(stmt, _COMPOUND_TYPES):
            own_lines.add(stmt.lineno)
            for sub in _sub_bodies(stmt):
                own_lines |= _fold_lines(sub)
            continue
        end = stmt.end_lineno or stmt.lineno
        own_lines.update(range(stmt.lineno, end + 1))
    return len(own_lines) + methods_total


@dataclass
class Measurement:
    file_lines: int
    classes: dict[str, int] = field(default_factory=dict)
    functions: dict[str, int] = field(default_factory=dict)


def measure_module(path: Path) -> Measurement:
    """Measure one module's executable-statement size, per file/class/function."""
    source = path.read_text(encoding="utf-8")
    tree = ast.parse(source)

    classes: dict[str, int] = {}
    functions: dict[str, int] = {}
    file_lines: set[int] = set()

    for index, stmt in enumerate(tree.body):
        if _is_docstring(stmt, index):
            continue
        if isinstance(stmt, ast.ClassDef):
            # The class's own header line counts toward its own total (below),
            # rolled into `total_file` via `sum(classes.values())` — not added
            # to `file_lines` directly, which would double it.
            classes[stmt.name] = 1 + _measure_class_body(stmt.body, stmt.name, functions)
            continue
        if isinstance(stmt, _DEF_TYPES):
            functions[stmt.name] = 1 + len(_fold_lines(stmt.body))
            continue
        if isinstance(stmt, _COMPOUND_TYPES):
            file_lines.add(stmt.lineno)
            for sub in _sub_bodies(stmt):
                file_lines |= _fold_lines(sub)
            continue
        end = stmt.end_lineno or stmt.lineno
        file_lines.update(range(stmt.lineno, end + 1))

    top_level_functions = sum(size for name, size in functions.items() if "." not in name)
    total_file = len(file_lines) + sum(classes.values()) + top_level_functions
    return Measurement(file_lines=total_file, classes=classes, functions=functions)


def _iter_src_files(src_root: Path = SRC_ROOT) -> list[Path]:
    """Every ``.py`` under ``src_root`` except the ``custom/`` strategies
    submodule — an unversioned git submodule this repo cannot pin (the
    ``STRATEGY_MODULES`` precedent in ``test_live_stop_path_is_inert.py``).
    Walking into it made the verdict depend on whether the submodule was
    checked out: a fresh worktree saw its baseline entries as deleted.
    """
    submodule = src_root / "core" / "strategies" / "custom"
    return sorted(path for path in src_root.rglob("*.py") if not path.is_relative_to(submodule))


def _print_baseline() -> None:
    """Entry point: ``python -m tests.unit.governance.test_size_caps --print-baseline``.

    Prints every current class/function overage in the ``SIZE_BASELINE``
    literal form this file embeds, so regenerating after a deliberate split
    is mechanical rather than hand-counted.
    """
    entries: list[tuple[str, int]] = []
    for path in _iter_src_files():
        rel = str(path.relative_to(REPO_ROOT))
        measurement = measure_module(path)
        for class_name, size in measurement.classes.items():
            if size > CLASS_CAP:
                entries.append((f"{rel}::{class_name}", size))
        for func_name, size in measurement.functions.items():
            if size > FUNCTION_CAP:
                entries.append((f"{rel}::{func_name}", size))

    entries.sort()
    print(f"SIZE_BASELINE: dict[str, int] = {{  # {len(entries)} entries")
    for key, size in entries:
        print(f'    "{key}": {size},')
    print("}")


class TestMeasureModuleMetric:
    """Pins the metric itself against synthetic sources — one fixture per
    metric ruling, plus the basics, so nobody has to reverse-engineer the
    metric from the baseline numbers alone.
    """

    def test_a_docstring_only_module_measures_zero(self, tmp_path):
        source = '"""\n' + ("line of prose\n" * 600) + '"""\n'
        path = tmp_path / "docstring_only.py"
        path.write_text(source)

        assert measure_module(path).file_lines == 0

    def test_a_compound_statement_counts_once(self, tmp_path):
        source = "def f():\n    if True:\n        x = 1\n        y = 2\n"
        path = tmp_path / "compound.py"
        path.write_text(source)

        # own header (1) + if header (1) + x=1 (1) + y=2 (1)
        assert measure_module(path).functions["f"] == 4

    def test_a_non_docstring_multiline_string_in_statement_position_counts_every_line(
        self, tmp_path
    ):
        source = (
            'def f():\n    query = (\n        "line1"\n        "line2"\n        "line3"\n    )\n'
        )
        path = tmp_path / "multiline.py"
        path.write_text(source)

        tree = ast.parse(source)
        assign = tree.body[0].body[0]
        span = (assign.end_lineno or assign.lineno) - assign.lineno + 1

        # own header (1) + every line the multi-line assign spans — not the
        # 1-line-only treatment a docstring gets, because this is not one.
        assert measure_module(path).functions["f"] == 1 + span

    def test_a_model_of_ten_annotated_fields_measures_ten(self, tmp_path):
        fields = "\n".join(f"    field_{i}: int = {i}" for i in range(10))
        path = tmp_path / "model.py"
        path.write_text(f"class Model:\n{fields}\n")

        # own header (1) + 10 AnnAssign lines
        assert measure_module(path).classes["Model"] == 11

    def test_a_function_with_a_20_line_closure_measures_its_own_lines_plus_20(self, tmp_path):
        closure_lines = "\n".join(f"        y{i} = {i}" for i in range(20))
        source = f"def outer():\n    x = 1\n    def inner():\n{closure_lines}\n    return inner\n"
        path = tmp_path / "closure.py"
        path.write_text(source)

        measurement = measure_module(path)

        # own header (1) + x=1 (1) + def-inner header (1) + return (1) + the
        # closure's own 20 lines, folded directly in.
        assert measurement.functions["outer"] == 24
        assert "inner" not in measurement.functions
        assert "outer.inner" not in measurement.functions


class TestScannedTree:
    """Which files the guard walks — pinned so its verdict cannot depend on
    whether the ``custom/`` submodule happens to be checked out.
    """

    def test_the_custom_submodule_is_excluded_from_the_walk(self, tmp_path):
        strategies = tmp_path / "core" / "strategies"
        (strategies / "custom").mkdir(parents=True)
        (strategies / "custom" / "private.py").write_text("x = 1\n")
        (strategies / "builtin.py").write_text("x = 1\n")

        assert _iter_src_files(tmp_path) == [strategies / "builtin.py"]

    def test_the_real_walk_is_not_vacuous(self):
        # Without this, a walk that found nothing — a moved SRC_ROOT, a
        # renamed tree — would pass every cap below vacuously.
        assert len(_iter_src_files()) > 100


class TestFileCap:
    """The hard cap: 500 lines, or a listed file's own recorded ceiling."""

    def test_no_file_exceeds_its_ceiling(self):
        offenders = []
        for path in _iter_src_files():
            rel = str(path.relative_to(REPO_ROOT))
            ceiling = FILE_ALLOWLIST.get(rel, FILE_CAP)
            size = measure_module(path).file_lines
            if size > ceiling:
                offenders.append((rel, size, ceiling))

        assert offenders == [], f"file(s) over their cap/ceiling: {offenders}"

    def test_the_allowlist_has_exactly_three_entries(self):
        """Not a magic number: the spec's own measured facts named exactly
        these three files as the honest raw-line overages that survive the
        executable-statement metric. A fourth would need its own disclosure.
        """
        assert len(FILE_ALLOWLIST) == 3

    def test_no_allowlisted_file_has_dropped_to_or_under_the_cap(self):
        """A listed file back under FILE_CAP is stale — the allowlist is a
        live ceiling, not a historical record.
        """
        stale = []
        for rel in FILE_ALLOWLIST:
            size = measure_module(REPO_ROOT / rel).file_lines
            if size <= FILE_CAP:
                stale.append((rel, size))

        assert stale == [], f"allowlist entries at/under the cap — remove them: {stale}"


def _locate_baseline_subject(key: str) -> tuple[int | None, str | None]:
    """Returns (current_size, kind) for a ``path::qualname`` baseline key, or
    ``(None, None)`` if the file or the qualname inside it no longer exists.
    """
    rel, _, name = key.partition("::")
    path = REPO_ROOT / rel
    if not path.exists():
        return None, None
    measurement = measure_module(path)
    if name in measurement.classes:
        return measurement.classes[name], "class"
    if name in measurement.functions:
        return measurement.functions[name], "function"
    return None, None


class TestSizeCapRatchet:
    """The ratchet: a class/function may not exceed its cap unless it is in
    ``SIZE_BASELINE``, and a baseline entry may not exceed its own recorded
    ceiling either — so the allowlist can only shrink, never grow silently.
    """

    def test_every_overage_is_baselined_or_under_its_cap(self):
        problems = []
        for path in _iter_src_files():
            rel = str(path.relative_to(REPO_ROOT))
            measurement = measure_module(path)
            for cap, items in (
                (CLASS_CAP, measurement.classes),
                (FUNCTION_CAP, measurement.functions),
            ):
                for name, size in items.items():
                    key = f"{rel}::{name}"
                    ceiling = SIZE_BASELINE.get(key, cap)
                    if size > ceiling:
                        problems.append((key, size, ceiling))

        assert problems == [], (
            f"class/function(es) over their cap or recorded ceiling — add a baseline entry "
            f"with a one-line reason, or shrink: {problems}"
        )

    def test_no_baseline_entry_has_dropped_to_or_under_its_cap(self):
        stale = []
        for key in SIZE_BASELINE:
            size, kind = _locate_baseline_subject(key)
            if size is None:
                stale.append((key, "renamed or deleted"))
                continue
            cap = CLASS_CAP if kind == "class" else FUNCTION_CAP
            if size <= cap:
                stale.append((key, size))

        assert stale == [], f"baseline entries renamed/deleted or at/under cap: {stale}"

    def test_baseline_entries_do_not_exceed_their_own_recorded_ceiling(self):
        """An entry is a *ceiling*, not licence to grow further unnoticed."""
        grown = []
        for key, ceiling in SIZE_BASELINE.items():
            size, _ = _locate_baseline_subject(key)
            if size is not None and size > ceiling:
                grown.append((key, size, ceiling))

        assert grown == [], f"baseline entries grew past their recorded ceiling: {grown}"

    def test_regenerating_the_baseline_reproduces_it_exactly(self):
        """The mechanical regeneration step this file's docstring describes,
        run as a test: if the tree has not changed, ``--print-baseline``'s
        output must equal ``SIZE_BASELINE`` exactly — proving the entry point
        and the embedded dict have not drifted apart.
        """
        regenerated: dict[str, int] = {}
        for path in _iter_src_files():
            rel = str(path.relative_to(REPO_ROOT))
            measurement = measure_module(path)
            for name, size in measurement.classes.items():
                if size > CLASS_CAP:
                    regenerated[f"{rel}::{name}"] = size
            for name, size in measurement.functions.items():
                if size > FUNCTION_CAP:
                    regenerated[f"{rel}::{name}"] = size

        assert regenerated == SIZE_BASELINE


if __name__ == "__main__":
    if "--print-baseline" in sys.argv:
        _print_baseline()
    else:
        print(__doc__)
