"""add per-timeframe date_range_start columns

Revision ID: 31151d95388b
Revises: 40ab8c820444
Create Date: 2026-10-03 22:41:20.207445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '31151d95388b'
down_revision: Union[str, Sequence[str], None] = '40ab8c820444'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalog_instruments', sa.Column('date_range_start_daily', postgresql.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('catalog_instruments', sa.Column('date_range_start_hourly', postgresql.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('catalog_instruments', sa.Column('date_range_start_minute', postgresql.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('catalog_instruments', sa.Column('date_range_start_5min', postgresql.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('catalog_instruments', sa.Column('date_range_start_30min', postgresql.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('catalog_instruments', 'date_range_start_30min')
    op.drop_column('catalog_instruments', 'date_range_start_5min')
    op.drop_column('catalog_instruments', 'date_range_start_minute')
    op.drop_column('catalog_instruments', 'date_range_start_hourly')
    op.drop_column('catalog_instruments', 'date_range_start_daily')
    # ### end Alembic commands ###
