"""add research studies

Revision ID: 3b798b125017
Revises: 31151d95388b
Create Date: 2026-10-04 10:25:09.091410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3b798b125017'
down_revision: Union[str, Sequence[str], None] = '31151d95388b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_studies',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('study_id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=81), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('hypothesis', sa.Text(), nullable=False),
    sa.Column('strategy_type', sa.String(length=100), nullable=False),
    sa.Column('symbols', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('timeframe', sa.String(length=20), nullable=False),
    sa.Column('catalog', sa.String(length=100), nullable=False),
    sa.Column('starting_balance', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('param_space', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_start', sa.Date(), nullable=False),
    sa.Column('is_end', sa.Date(), nullable=False),
    sa.Column('oos_start', sa.Date(), nullable=False),
    sa.Column('oos_end', sa.Date(), nullable=False),
    sa.Column('pass_criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('trial_budget', sa.Integer(), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('status_reason', sa.Text(), nullable=True),
    sa.Column('contaminated', sa.Boolean(), nullable=False),
    sa.Column('contamination_reason', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('exploring', 'frozen', 'tested', 'promoted', 'rejected', 'parked')", name='chk_study_status'),
    sa.CheckConstraint('is_end < oos_start', name='chk_study_holdout_after'),
    sa.CheckConstraint('is_start <= is_end', name='chk_study_in_sample'),
    sa.CheckConstraint('oos_start <= oos_end', name='chk_study_out_of_sample'),
    sa.CheckConstraint('trial_budget > 0', name='chk_study_budget'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('idx_research_studies_status', 'research_studies', ['status'], unique=False)
    op.create_index(op.f('ix_research_studies_study_id'), 'research_studies', ['study_id'], unique=True)
    op.create_table('research_candidates',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('study_pk', sa.BigInteger(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('source_run_id', sa.UUID(), nullable=False),
    sa.Column('strategy_type', sa.String(length=100), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('timeframe', sa.String(length=20), nullable=False),
    sa.Column('catalog', sa.String(length=100), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('starting_balance', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('fill_seed', sa.Integer(), nullable=False),
    sa.Column('git_commit', sa.String(length=40), nullable=True),
    sa.Column('git_dirty', sa.Boolean(), nullable=True),
    sa.Column('strategies_commit', sa.String(length=40), nullable=True),
    sa.Column('candidate_hash', sa.String(length=64), nullable=False),
    sa.Column('frozen_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['study_pk'], ['research_studies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id'),
    sa.UniqueConstraint('study_pk', 'version', name='uq_candidate_version')
    )
    op.create_table('research_study_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('study_pk', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['study_pk'], ['research_studies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_research_study_events_study', 'research_study_events', ['study_pk', 'id'], unique=False)
    op.create_table('research_trials',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('study_pk', sa.BigInteger(), nullable=False),
    sa.Column('candidate_pk', sa.BigInteger(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('job_id', sa.String(length=40), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('counted', sa.Boolean(), nullable=False),
    sa.Column('strategy_type', sa.String(length=100), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('config_hash', sa.String(length=64), nullable=False),
    sa.Column('start', sa.Date(), nullable=False),
    sa.Column('end', sa.Date(), nullable=False),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('settled_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('in_sample', 'benchmark', 'out_of_sample', 'reproduction')", name='chk_trial_role'),
    sa.CheckConstraint("state IN ('pending', 'completed', 'void')", name='chk_trial_state'),
    sa.ForeignKeyConstraint(['candidate_pk'], ['research_candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['study_pk'], ['research_studies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    op.create_index('idx_research_trials_run', 'research_trials', ['run_id'], unique=False)
    op.create_index('idx_research_trials_study', 'research_trials', ['study_pk', 'id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_research_trials_study', table_name='research_trials')
    op.drop_index('idx_research_trials_run', table_name='research_trials')
    op.drop_table('research_trials')
    op.drop_index('idx_research_study_events_study', table_name='research_study_events')
    op.drop_table('research_study_events')
    op.drop_table('research_candidates')
    op.drop_index(op.f('ix_research_studies_study_id'), table_name='research_studies')
    op.drop_index('idx_research_studies_status', table_name='research_studies')
    op.drop_table('research_studies')
    # ### end Alembic commands ###
