"""add run provenance to backtest_runs

Revision ID: 6377e1ce0bf9
Revises: 85c949ac0374
Create Date: 2026-10-03 15:11:15.047642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6377e1ce0bf9'
down_revision: Union[str, Sequence[str], None] = '85c949ac0374'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backtest_runs', sa.Column('git_commit', sa.String(length=40), nullable=True))
    op.add_column('backtest_runs', sa.Column('git_dirty', sa.Boolean(), nullable=True))
    op.add_column('backtest_runs', sa.Column('strategies_commit', sa.String(length=40), nullable=True))
    op.add_column('backtest_runs', sa.Column('config_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_backtest_runs_config_hash'), 'backtest_runs', ['config_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_backtest_runs_config_hash'), table_name='backtest_runs')
    op.drop_column('backtest_runs', 'config_hash')
    op.drop_column('backtest_runs', 'strategies_commit')
    op.drop_column('backtest_runs', 'git_dirty')
    op.drop_column('backtest_runs', 'git_commit')
    # ### end Alembic commands ###
