"""add per-timeframe date_range_end columns

Revision ID: 986f8a8d5bb4
Revises: 9f3c1a72b4e8
Create Date: 2026-07-01 13:07:30.271807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '986f8a8d5bb4'
down_revision: Union[str, Sequence[str], None] = '9f3c1a72b4e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalog_instruments', sa.Column('date_range_end_daily', postgresql.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('catalog_instruments', sa.Column('date_range_end_hourly', postgresql.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('catalog_instruments', sa.Column('date_range_end_minute', postgresql.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('catalog_instruments', sa.Column('date_range_end_5min', postgresql.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('catalog_instruments', sa.Column('date_range_end_30min', postgresql.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('catalog_instruments', 'date_range_end_30min')
    op.drop_column('catalog_instruments', 'date_range_end_5min')
    op.drop_column('catalog_instruments', 'date_range_end_minute')
    op.drop_column('catalog_instruments', 'date_range_end_hourly')
    op.drop_column('catalog_instruments', 'date_range_end_daily')
    # ### end Alembic commands ###
