"""create backtest_runs and performance_metrics tables with timezone support

Revision ID: 9c7d5c448387
Revises: 7d28f3a711e7
Create Date: 2025-10-26 12:11:08.261867

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9c7d5c448387"
down_revision: Union[str, Sequence[str], None] = "7d28f3a711e7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "backtest_runs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("strategy_name", sa.String(length=255), nullable=False),
        sa.Column("strategy_type", sa.String(length=100), nullable=False),
        sa.Column("instrument_symbol", sa.String(length=50), nullable=False),
        sa.Column("start_date", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("end_date", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("initial_capital", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("data_source", sa.String(length=100), nullable=False),
        sa.Column("execution_status", sa.String(length=20), nullable=False),
        sa.Column(
            "execution_duration_seconds",
            sa.Numeric(precision=10, scale=3),
            nullable=False,
        ),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "config_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("reproduced_from_run_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("end_date > start_date", name="chk_date_range"),
        sa.CheckConstraint(
            "execution_duration_seconds >= 0", name="chk_execution_duration"
        ),
        sa.CheckConstraint("initial_capital > 0", name="chk_initial_capital"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_backtest_runs_created_id",
        "backtest_runs",
        ["created_at", "id"],
        unique=False,
    )
    op.create_index(
        "idx_backtest_runs_strategy_created_id",
        "backtest_runs",
        ["strategy_name", "created_at", "id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_backtest_runs_run_id"), "backtest_runs", ["run_id"], unique=True
    )
    op.create_table(
        "performance_metrics",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("backtest_run_id", sa.BigInteger(), nullable=False),
        sa.Column("total_return", sa.Numeric(precision=15, scale=6), nullable=False),
        sa.Column("final_balance", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("cagr", sa.Numeric(precision=15, scale=6), nullable=True),
        sa.Column("sharpe_ratio", sa.Numeric(precision=15, scale=6), nullable=True),
        sa.Column("sortino_ratio", sa.Numeric(precision=15, scale=6), nullable=True),
        sa.Column("max_drawdown", sa.Numeric(precision=15, scale=6), nullable=True),
        sa.Column(
            "max_drawdown_date", postgresql.TIMESTAMP(timezone=True), nullable=True
        ),
        sa.Column("calmar_ratio", sa.Numeric(precision=15, scale=6), nullable=True),
        sa.Column("volatility", sa.Numeric(precision=15, scale=6), nullable=True),
        sa.Column("total_trades", sa.Integer(), nullable=False),
        sa.Column("winning_trades", sa.Integer(), nullable=False),
        sa.Column("losing_trades", sa.Integer(), nullable=False),
        sa.Column("win_rate", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("profit_factor", sa.Numeric(precision=15, scale=6), nullable=True),
        sa.Column("expectancy", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column("avg_win", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column("avg_loss", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "total_trades = winning_trades + losing_trades",
            name="chk_trade_count_consistency",
        ),
        sa.ForeignKeyConstraint(
            ["backtest_run_id"], ["backtest_runs.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("backtest_run_id"),
    )
    op.create_index(
        "idx_metrics_backtest_run_id",
        "performance_metrics",
        ["backtest_run_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_metrics_backtest_run_id", table_name="performance_metrics")
    op.drop_table("performance_metrics")
    op.drop_index(op.f("ix_backtest_runs_run_id"), table_name="backtest_runs")
    op.drop_index("idx_backtest_runs_strategy_created_id", table_name="backtest_runs")
    op.drop_index("idx_backtest_runs_created_id", table_name="backtest_runs")
    op.drop_table("backtest_runs")
    # ### end Alembic commands ###
