"""add catalog_dividends and catalog_stock_splits tables

Revision ID: b3accfdb64bd
Revises: 79f6e07bee8b
Create Date: 2026-06-03 18:20:46.175533

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b3accfdb64bd"
down_revision: Union[str, Sequence[str], None] = "79f6e07bee8b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "catalog_dividends",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("catalog_name", sa.String(length=50), nullable=False),
        sa.Column("ticker", sa.String(length=20), nullable=False),
        sa.Column("ex_date", sa.Date(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "catalog_name", "ticker", "ex_date", name="uq_catalog_dividends_catalog_ticker_date"
        ),
    )
    op.create_index(
        "ix_catalog_dividends_catalog_ticker",
        "catalog_dividends",
        ["catalog_name", "ticker"],
        unique=False,
    )
    op.create_table(
        "catalog_stock_splits",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("catalog_name", sa.String(length=50), nullable=False),
        sa.Column("ticker", sa.String(length=20), nullable=False),
        sa.Column("effective_date", sa.Date(), nullable=False),
        sa.Column("ratio", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "catalog_name",
            "ticker",
            "effective_date",
            name="uq_catalog_stock_splits_catalog_ticker_date",
        ),
    )
    op.create_index(
        "ix_catalog_stock_splits_catalog_ticker",
        "catalog_stock_splits",
        ["catalog_name", "ticker"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_catalog_stock_splits_catalog_ticker", table_name="catalog_stock_splits")
    op.drop_table("catalog_stock_splits")
    op.drop_index("ix_catalog_dividends_catalog_ticker", table_name="catalog_dividends")
    op.drop_table("catalog_dividends")
    # ### end Alembic commands ###
