"""add trading_sessions and paper run support

Revision ID: d08dfbd393f0
Revises: a436f35f525c
Create Date: 2026-08-19 08:20:15.595284

The phase's SINGLE Alembic migration (epics.md:367-371) -- every later story in
this phase reads a row this migration creates, so it is written once, up front,
rather than split across the epic.

Three independent pieces of DDL:

1. ``trading_sessions`` -- the system of record for a named paper-trading
   session and its frozen ``SessionSpec`` (JSONB, write-once). ``status`` is a
   Postgres enum whose labels are deliberately lowercase
   (``created``/``running``/``stopped``/``sealed``), matching ``SessionStatus``'s
   *values* rather than its member names -- see the ORM column's
   ``values_callable`` for why that is not the default.

2. ``backtest_runs.run_type`` -- a plain ``String(20)`` distinguishing a
   ``'backtest'`` row (the default, and every existing row) from a ``'paper'``
   row a sealed session writes (Epic 5). No ``backtest_runs`` row is created
   here, nor at session start -- only at seal (AR5). A pre-created row would
   surface unfinished sessions in the existing list views and break the
   zero-UI-change success criterion this phase is held to.

3. ``trades`` widening -- ``backtest_run_id`` becomes nullable and a new
   nullable ``session_id`` (targeting ``trading_sessions.id``, the BigInteger
   key, not the UUID business key -- mirroring ``backtest_run_id ->
   backtest_runs.id``) is added, with a CHECK ensuring every trade still has
   an owner: ``backtest_run_id IS NOT NULL OR session_id IS NOT
   NULL``. Nothing writes a session-owned trade until Epic 3; this migration
   only makes room for it.

   The CHECK is a disjunction -- "at least one owner", not "exactly one". That
   is deliberate: a session-owned trade carries only ``session_id`` while the
   session runs, and seal (Epic 5) backfills ``backtest_run_id`` so the
   existing backtest queries and views see it unchanged, after which the row
   legitimately holds BOTH owners. Do not tighten this to
   ``num_nonnulls(backtest_run_id, session_id) = 1``; it would refuse every
   sealed trade.

This migration is hand-written, not autogenerated: the ORM and the migration
chain have pre-existing drift (``34f3c8e99016`` creates
``idx_trades_backtest_run_id`` where the ORM's ``index=True`` wants
``ix_trades_backtest_run_id``), so autogenerate's answer depends on which
database it is pointed at rather than being a specification. That drift is
out of scope here and is not "repaired" by this migration.

Verified against the live database before this migration was written:
133 ``backtest_runs`` rows and 14 982 ``trades`` rows, all satisfying the new
CHECK (every existing ``backtest_run_id`` is non-null). Every column added
here is either metadata-only on PG 11+ (nullable relaxations, new nullable
columns, a NOT NULL column with a ``server_default``) or a CHECK that scans
the existing rows and validates cleanly against them.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d08dfbd393f0"
down_revision: Union[str, Sequence[str], None] = "a436f35f525c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# The migration owns the CREATE TYPE / DROP TYPE DDL. ``create_type=False``
# stops SQLAlchemy from auto-emitting its own CREATE TYPE (which would collide
# with the explicit ``.create()`` below). Labels are lowercase, matching
# SessionStatus's values -- not its member names (architecture.md:380-381).
session_status_enum = postgresql.ENUM(
    "created", "running", "stopped", "sealed", name="session_status", create_type=False
)


def upgrade() -> None:
    """Create trading_sessions, widen backtest_runs and trades for paper trading."""
    # 1. Enum type MUST exist before the column that uses it.
    session_status_enum.create(op.get_bind(), checkfirst=True)

    # 2. trading_sessions table. Uniqueness on session_id/name is created as
    # unique INDEXES below, never sa.UniqueConstraint here -- the ORM's
    # `unique=True, index=True` emits a unique index and no table-level
    # constraint, and the two naming schemes would otherwise drift forever
    # with no test able to see it (fixtures build from the ORM, not this
    # migration).
    op.create_table(
        "trading_sessions",
        sa.Column("id", sa.BigInteger(), nullable=False, autoincrement=True),
        sa.Column("session_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("status", session_status_enum, nullable=False),
        sa.Column("spec", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("linked_backtest_run_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("sealed_run_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("last_started_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("last_stopped_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("sealed_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("last_heartbeat_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("last_bar_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["linked_backtest_run_id"], ["backtest_runs.run_id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_trading_sessions_session_id"), "trading_sessions", ["session_id"], unique=True
    )
    op.create_index(op.f("ix_trading_sessions_name"), "trading_sessions", ["name"], unique=True)
    op.create_index("ix_trading_sessions_status", "trading_sessions", ["status"], unique=False)

    # 3. backtest_runs.run_type -- NOT NULL with a server_default, so this is a
    # metadata-only change against the 133 existing rows (PG 11+), not a
    # 133-row rewrite.
    op.add_column(
        "backtest_runs",
        sa.Column("run_type", sa.String(length=20), nullable=False, server_default="backtest"),
    )

    # 4. trades widening. session_id targets trading_sessions.id (BigInteger),
    # not trading_sessions.session_id (UUID) -- see the ORM column's docstring
    # for the full rationale.
    op.add_column("trades", sa.Column("session_id", sa.BigInteger(), nullable=True))
    op.create_foreign_key(
        "trades_session_id_fkey", "trades", "trading_sessions", ["session_id"], ["id"]
    )
    op.create_index(op.f("ix_trades_session_id"), "trades", ["session_id"], unique=False)
    op.alter_column("trades", "backtest_run_id", existing_type=sa.BigInteger(), nullable=True)
    # CHECK goes last, after session_id exists, or it references an unknown
    # column. It DOES scan all 14 982 existing rows to validate -- they all
    # hold a non-null backtest_run_id today, so it validates cleanly; at this
    # size the scan costs milliseconds.
    op.create_check_constraint(
        "chk_trades_owner", "trades", "backtest_run_id IS NOT NULL OR session_id IS NOT NULL"
    )


def downgrade() -> None:
    """Reverse the upgrade, refusing if any trade belongs to a session.

    The guard runs FIRST, before any DDL. Alembic's per-migration transaction
    would roll back a later refusal anyway, but a downgrade that drops the
    CHECK before deciding whether it can proceed reads as if the destruction
    were intended.
    """
    orphans = (
        op.get_bind()
        .execute(sa.text("SELECT count(*) FROM trades WHERE backtest_run_id IS NULL"))
        .scalar_one()
    )
    if orphans:
        raise RuntimeError(
            f"{orphans} trade(s) belong to a session and have no backtest_run_id, so "
            "backtest_run_id cannot be restored to NOT NULL. Seal the owning sessions "
            "(which backfills backtest_run_id) or delete those trades first."
        )

    op.drop_constraint("chk_trades_owner", "trades", type_="check")
    op.alter_column("trades", "backtest_run_id", existing_type=sa.BigInteger(), nullable=False)
    # The FK (trades_session_id_fkey) and the index (ix_trades_session_id) are
    # both owned solely by this column and are dropped automatically with it.
    op.drop_column("trades", "session_id")
    op.drop_column("backtest_runs", "run_type")

    op.drop_index("ix_trading_sessions_status", table_name="trading_sessions")
    op.drop_index(op.f("ix_trading_sessions_name"), table_name="trading_sessions")
    op.drop_index(op.f("ix_trading_sessions_session_id"), table_name="trading_sessions")
    op.drop_table("trading_sessions")
    # op.drop_table does NOT drop the enum type -- drop it explicitly, last, or
    # a subsequent upgrade fails with "type already exists".
    session_status_enum.drop(op.get_bind(), checkfirst=True)
