"""add country and state to catalog_instruments

Revision ID: dbec2c1f25a6
Revises: b3accfdb64bd
Create Date: 2026-06-03 20:46:58.773294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbec2c1f25a6'
down_revision: Union[str, Sequence[str], None] = 'b3accfdb64bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalog_instruments', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('catalog_instruments', sa.Column('state', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('catalog_instruments', 'state')
    op.drop_column('catalog_instruments', 'country')
    # ### end Alembic commands ###
