"""The boundary the runner installs around each strategy's order calls
(Story 3.2, AC #4/#5/#6).

Owns: :func:`install_order_path` — the instance-level wrap that suppresses
order-creating strategy calls while the connection is known lost or
unobserved — and :class:`OrderEventObserver`, the first consumer of
Nautilus's own order events, which logs ``order.submitted`` with the
bar-close-to-submit latency NFR1 measures.

Does not own: the wiring (``src/core/live_session_runner.py`` calls
:func:`install_order_path` between ``materialise_strategy`` and
``add_strategy``, and subscribes the observer's handlers in
``_phase_subscribe``), the suppression *predicate* itself
(``src/core/live_connection_monitor.py``'s ``submission_withheld`` — this
module only *consults* it), or anything about a fill, a rejection or a
lifecycle beyond ``OrderSubmitted`` (Story 3.3).

**Why a new module, not `live_strategy_guard.py` or the runner.**
``live_strategy_guard.py`` and ``live_session_runner.py`` are both in
``STOP_PATH_MODULES`` (``tests/unit/core/test_live_stop_path_is_inert.py``),
whose scan forbids any **call** to a forbidden order method anywhere in the
module — call-callee collection, so it catches ``self.close_all_positions(...)``,
``node.trader.close_all_positions(...)`` and a bare ``close_all_positions(...)``
alike. This module legitimately calls the wrapped originals, so it stays
deliberately OUT of that list — the runner and the guard call only
:func:`install_order_path`, a name that is not itself forbidden, so their own
scans stay clean.

**Mechanism, measured before writing this** (Story 3.2 Task 1, Dev Agent
Record): instance-level attribute assignment reliably shadows
``submit_order``/``close_position`` for the strategy's own Python call sites —
the same mechanism ``LiveStrategyGuard.wrap`` already uses for
``handle_bar``/``handle_event``. Measured directly against the installed
wheel: ``close_position``'s own internal ``self.submit_order(...)`` call
(``trading/strategy.pyx:1303``) *does* reach a wrapped ``submit_order`` too —
Cython's ``self.method()`` self-call for a ``cpdef`` method on a Python
subclass instance honours a Python-level instance ``__dict__`` override. This
corrects the pre-measurement Dev Notes hypothesis that it would bypass one;
it does not change the mechanism, because suppression must still stop the
*outer* ``close_position`` call (its own cache reads, its own log lines), not
merely rely on an inner call aliasing into an already-wrapped sibling.

**Cancels are deliberately not suppressed.** Cancelling an order while
disconnected creates no new exposure and cannot "blindly trade" — the
opposite of what this boundary exists to prevent. Only the four
order/position-*creating* calls are wrapped; see :data:`ORDER_CREATING_METHODS`.

**The suppression path is contained; the pass-through path is not.**
Consulting the predicate and logging a suppression is new code sitting
in front of a call that used to go straight through, so *that* part is
wrapped in its own ``try``/``except`` — any failure there suppresses (fail
closed) and logs ``order.suppression_failed`` rather than raising into
strategy code. But when the predicate says the order may proceed, the wrapper
calls straight through with **no** ``try`` around it: an exception from the
real Nautilus call must propagate exactly as it would from the unwrapped
method, which is what AC #1's "no live-specific strategy variant" requires
and what Story 2.7's ``handle_bar``/``handle_event`` boundary (already
wrapping every strategy call this module's calls happen inside) already
contains.

**The observer contains everything, always** — a raise from a msgbus handler
re-enters ``MessageBus.publish_c``, which has no ``try`` around
``sub.handler(msg)``, and ends at Nautilus's own silent ``os._exit(1)`` with
zero output (the Story 2.7 lesson). Nothing here may ever let that happen.

**Latency anchor**: the venue bar close (``bar.ts_event``), not handler entry
— NFR1 measures the live-vs-backtest divergence window, which includes
delivery lag. Known hazards, stated rather than hidden: ``live_bars.received``
appears twice per bar (Nautilus C logger + structlog), and the first bar
after subscribe can be a backfill bar (P3) — a live-transcript reader must
read latency from steady-state bars, not the first one. ``OrderSubmitted`` is
generated by the **execution client** (the adapter), not by
``Strategy.submit_order`` itself, which only publishes the order's own
``init_event_c()`` (``OrderInitialized``) on the same topic first (measured,
Task 1.2) — so this module filters on event *type*, never merely on topic.
"""

from collections.abc import Callable
from typing import Any

#: The order/position-*creating* strategy methods this module wraps. A
#: subset of `tests/unit/core/test_live_stop_path_is_inert.py`'s
#: `FORBIDDEN_ORDER_METHODS` (production cannot import from `tests/`, so the
#: relationship is asserted there against a duplicated literal, per
#: CLAUDE.md's "Membership-pinned lists" convention) — `cancel_all_orders`
#: and `cancel_order` are deliberately excluded; see the module docstring.
ORDER_CREATING_METHODS: frozenset[str] = frozenset(
    {"submit_order", "submit_order_list", "close_position", "close_all_positions"}
)

#: AR41's `order.*` namespace. Dotted lowercase past tense, no `close`/
#: `halt`/`kill`/`pause`/`finalize` stem anywhere in an operator-facing string
#: this module emits (AR36).
SUPPRESSED_EVENT = "order.suppressed"
SUBMITTED_EVENT = "order.submitted"

#: The wildcard topic `Strategy.register()` publishes order events on —
#: `events.order.{strategy_id}` (`trading/strategy.pyx:314-315`, measured
#: Task 1.2). Matches the `BAR_TOPIC` precedent (`live_session_node.py`).
ORDER_EVENTS_TOPIC = "events.order*"


def install_order_path(strategy: Any, monitor: Any, log: Any) -> None:
    """Wrap ``strategy``'s order-creating methods with the suppression check.

    Must be called **before** ``Trader.add_strategy`` — the same ordering
    constraint ``StrategyGuard.wrap`` documents for the same reason: Nautilus
    binds these as plain instance attributes and nothing re-reads them later,
    so wrapping after materialisation but before registration is the only
    window in which every subsequent call — including the strategy's own
    internal ones — sees the wrapped version.

    Args:
        strategy: The materialised strategy. Duck-typed — this module never
            imports ``nautilus_trader``, matching ``live_strategy_guard.py``'s
            framework-free discipline.
        monitor: Anything with a ``submission_withheld`` bool property — in
            production a ``ConnectionMonitor``, in tests a stub.
        log: A structlog logger, ideally already bound to ``session_id``.
    """
    for method_name in ORDER_CREATING_METHODS:
        base = getattr(strategy, method_name)
        setattr(strategy, method_name, _wrap(method_name, base, monitor, log))


def _wrap(method_name: str, base: Callable[..., Any], monitor: Any, log: Any) -> Callable[..., Any]:
    """Build the instance-level replacement for one order-creating method."""

    def wrapped(*args: Any, **kwargs: Any) -> Any:
        try:
            withheld = bool(monitor.submission_withheld)
            if withheld:
                _log_suppressed(log, method_name, args, kwargs)
        except Exception as exc:  # noqa: BLE001 - the wrapper's own logic must never raise
            log.error(
                "order.suppression_failed",
                method=method_name,
                error_type=type(exc).__name__,
            )
            return None
        if withheld:
            return None
        return base(*args, **kwargs)

    return wrapped


def _log_suppressed(
    log: Any, method_name: str, args: tuple[Any, ...], kwargs: dict[str, Any]
) -> None:
    """Log what this specific call carries, and nothing it does not.

    Never invents a value: a wrapped ``submit_order`` has a real order object
    with a ``client_order_id``; a wrapped ``close_position`` has a position,
    not yet an order, so it never gets one.
    """
    log.warning(SUPPRESSED_EVENT, method=method_name, **_describe(method_name, args, kwargs))


def _describe(method_name: str, args: tuple[Any, ...], kwargs: dict[str, Any]) -> dict[str, str]:
    described: dict[str, str] = {}
    if method_name == "submit_order":
        order = args[0] if args else kwargs.get("order")
        _add_instrument(described, order)
        _add_client_order_id(described, order)
    elif method_name == "submit_order_list":
        order_list = args[0] if args else kwargs.get("order_list")
        orders = getattr(order_list, "orders", None) or ()
        if orders:
            _add_instrument(described, orders[0])
    elif method_name == "close_position":
        position = args[0] if args else kwargs.get("position")
        _add_instrument(described, position)
    elif method_name == "close_all_positions":
        instrument_id = args[0] if args else kwargs.get("instrument_id")
        if instrument_id is not None:
            described["instrument_id"] = str(instrument_id)
    return described


def _add_instrument(described: dict[str, str], source: Any) -> None:
    instrument_id = getattr(source, "instrument_id", None)
    if instrument_id is not None:
        described["instrument_id"] = str(instrument_id)


def _add_client_order_id(described: dict[str, str], source: Any) -> None:
    client_order_id = getattr(source, "client_order_id", None)
    if client_order_id is not None:
        described["client_order_id"] = str(client_order_id)


class OrderEventObserver:
    """Nautilus's first order-event consumer (Story 3.2, AC #5/#6).

    Two message-bus handlers, wired by the runner in ``_phase_subscribe``
    directly after the existing ``BAR_TOPIC`` subscribe (Task 5):

    - :meth:`note_bar` — records ``instrument_id -> bar.ts_event``, purely to
      anchor NFR1's latency measurement. Independent of
      ``SessionSteadyState.note_bar``'s own liveness counter; this one exists
      for a different reason and neither reads the other.
    - :meth:`handle_order_event` — ignores anything but ``OrderSubmitted``.
      Story 3.3 owns the rest of the order lifecycle; this is also what makes
      an ``OrderRejected`` delivered today contained rather than crashing
      (AC #3's rejection-tolerance guard). ``submit_order`` itself publishes
      the order's own ``OrderInitialized`` on the **same topic** first
      (measured, Task 1.2) — filtering is on event *type*, never merely on
      topic.

    Both handlers contain every exception internally and never raise: a raise
    from a msgbus handler re-enters ``MessageBus.publish_c``, which has no
    ``try`` around ``sub.handler(msg)``, and ends at Nautilus's own silent
    ``os._exit(1)`` (the Story 2.7 lesson).

    Args:
        log: A structlog logger already bound to ``session_id``. Contextvars
            reach asyncio tasks created after the bind but are **empty** on
            ``ThreadPoolExecutor`` threads (Task 4.4) — this class never
            relies on ambient context, only on what it is handed.
    """

    def __init__(self, log: Any) -> None:
        self._log = log
        self._last_bar_ts_event: dict[str, int] = {}

    def note_bar(self, bar: Any) -> None:
        """Record the venue close instant for this bar's instrument."""
        try:
            instrument_id = str(bar.bar_type.instrument_id)
            self._last_bar_ts_event[instrument_id] = bar.ts_event
        except Exception as exc:  # noqa: BLE001 - a msgbus handler must never raise
            self._log.error(
                "order.observer_failed", stage="note_bar", error_type=type(exc).__name__
            )

    def handle_order_event(self, event: Any) -> None:
        """Handle one ``events.order*`` delivery."""
        try:
            if type(event).__name__ != "OrderSubmitted":
                return
            self._log_submitted(event)
        except Exception as exc:  # noqa: BLE001 - a msgbus handler must never raise
            self._log.error(
                "order.observer_failed", stage="handle_order_event", error_type=type(exc).__name__
            )

    def _log_submitted(self, event: Any) -> None:
        """The latency anchor is the venue bar close (``bar.ts_event``), not
        handler entry — NFR1 measures the live-vs-backtest divergence window,
        which includes delivery lag. Absent, never fabricated, when no bar
        has been observed yet for this instrument.
        """
        fields: dict[str, Any] = {
            "client_order_id": str(event.client_order_id),
            "instrument_id": str(event.instrument_id),
        }
        bar_ts_event = self._last_bar_ts_event.get(str(event.instrument_id))
        if bar_ts_event is not None:
            fields["bar_close_to_submit_ms"] = (event.ts_init - bar_ts_event) / 1_000_000
        self._log.info(SUBMITTED_EVENT, **fields)
