name: Claude PR Review

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main, develop]

jobs:
  claude-review:
    name: Claude Code Review
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' && !contains(github.event.pull_request.labels.*.name, 'skip-claude-review') }}

    permissions:
      contents: read
      pull-requests: write
      issues: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v42
        with:
          base_sha: ${{ github.event.pull_request.base.sha }}
          sha: ${{ github.event.pull_request.head.sha }}
          files: |
            **/*.py
            **/*.md
            **/*.yml
            **/*.yaml
            **/*.toml
            **/*.json

      - name: Setup Python
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run Claude PR Review
        if: steps.changed-files.outputs.any_changed == 'true'
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
          BASE_SHA: ${{ github.event.pull_request.base.sha }}
          HEAD_SHA: ${{ github.event.pull_request.head.sha }}
          CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          echo "Debug: Environment variables check"
          echo "ANTHROPIC_API_KEY: $(if [ -n "$ANTHROPIC_API_KEY" ]; then echo "Set"; else echo "Not set"; fi)"
          echo "PR_NUMBER: $PR_NUMBER"
          echo "REPO_OWNER: $REPO_OWNER"
          echo "REPO_NAME: $REPO_NAME"
          echo "CHANGED_FILES: $CHANGED_FILES"

          if [ -z "$ANTHROPIC_API_KEY" ]; then
            echo "Error: ANTHROPIC_API_KEY secret is not configured"
            echo "Please add the ANTHROPIC_API_KEY secret in repository settings"
            exit 1
          fi

          python .github/scripts/claude_reviewer.py

      - name: Comment if API key missing
        if: steps.changed-files.outputs.any_changed == 'true' && env.ANTHROPIC_API_KEY == ''
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🤖 **Claude Review Setup Required**\n\nThe automated code review is not working because the `ANTHROPIC_API_KEY` secret is not configured.\n\n**To fix this:**\n1. Go to repository Settings → Secrets and variables → Actions\n2. Add a new secret named `ANTHROPIC_API_KEY`\n3. Set the value to your Anthropic API key\n\nOnce configured, the automated Claude reviews will work on future PRs.'
            });

      - name: Comment if no changes
        if: steps.changed-files.outputs.any_changed == 'false'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🤖 **Claude Review**: No reviewable files changed in this PR (Python, Markdown, YAML, TOML, JSON). Skipping automated review.'
            });