name: Test Claude Review (Manual)

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR number to review'
        required: true
        default: '1'

jobs:
  test-claude:
    name: Test Claude Review
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check environment
        run: |
          echo "🔧 Environment Check:"
          echo "  - PR Number: ${{ github.event.inputs.pr_number }}"
          echo "  - Repository: ${{ github.repository }}"
          echo "  - ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY != '' && '✓ Set' || '✗ Missing' }}"
          echo "  - GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN != '' && '✓ Set' || '✗ Missing' }}"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install requests

      - name: Test Claude API connectivity
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: |
          if [ -z "$ANTHROPIC_API_KEY" ]; then
            echo "❌ ANTHROPIC_API_KEY is not set"
            echo "Please add your Anthropic API key as a repository secret named 'ANTHROPIC_API_KEY'"
            echo "Go to: Repository Settings → Secrets and variables → Actions → New repository secret"
            exit 1
          else
            echo "✅ ANTHROPIC_API_KEY is configured"
            # Test API key format
            python -c '
import os
api_key = os.getenv("ANTHROPIC_API_KEY")
if api_key and api_key.startswith("sk-ant-"):
    print("✅ API key format looks correct")
else:
    print("⚠️  API key format may be incorrect")
    print("Expected format: sk-ant-...")
'
          fi

      - name: Post test comment
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = ${{ github.event.inputs.pr_number }};
            const hasApiKey = '${{ secrets.ANTHROPIC_API_KEY }}' !== '';

            let message = '## 🤖 Claude Review Configuration Test\n\n';

            if (hasApiKey) {
              message += '✅ **ANTHROPIC_API_KEY**: Configured correctly\n';
              message += '✅ **GITHUB_TOKEN**: Available\n';
              message += '✅ **Workflow**: Can execute successfully\n\n';
              message += 'Claude code reviews should work on your PRs! 🎉\n\n';
              message += '_This was a manual test. The automated review will run on future PR commits._';
            } else {
              message += '❌ **ANTHROPIC_API_KEY**: Not configured\n';
              message += '❌ **Claude Reviews**: Will not work until API key is added\n\n';
              message += '### Setup Instructions:\n';
              message += '1. Go to Repository Settings → Secrets and variables → Actions\n';
              message += '2. Click "New repository secret"\n';
              message += '3. Name: `ANTHROPIC_API_KEY`\n';
              message += '4. Value: Your Anthropic API key (starts with `sk-ant-`)\n\n';
              message += '_Get your API key from: https://console.anthropic.com/_';
            }

            github.rest.issues.createComment({
              issue_number: prNumber,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: message
            });